-- MIGRATION: 20260105_enrich_cases.sql
-- OBJECTIVE: Enrich cases table with detailed profile data for the Lawyer Dashboard

alter table cases 
  add column if not exists ai_summary text,
  add column if not exists client_profile jsonb default '{}'::jsonb,
  add column if not exists notes text;

-- Comment on columns for clarity
comment on column cases.ai_summary is 'Narrative summary generated by AI for the lawyer';
comment on column cases.client_profile is 'Structured JSON data (job, salary, family, antecedents)';
comment on column cases.notes is 'Internal notes by the lawyer or system';
